service: cas-agd-tlmdcn-availability
useDotenv: true

plugins:
  - "@nearst/serverless-dynalite"
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  environment:
    SERVICE_NAME: ${self:service}
    DYNAMODB_TABLE_MEDICAP_BOOKING: ${self:service}-${sls:stage}-medicap-booking
    DYNAMODB_TABLE_MEDICAP_PRE_BOOKING: ${self:service}-${sls:stage}-medicap-pre-booking
    DYNAMODB_TABLE_MEDICAP_RELEASE: ${self:service}-${sls:stage}-medicap-release
    DYNAMODB_TABLE_MEDICAP_CALENDAR: ${self:service}-${sls:stage}-medicap-calendar
    DYNAMODB_TABLE_MEDICAP_EXCEPTION: ${self:service}-${sls:stage}-medicap-exception
  apiGateway:
    restApiId: ${self:custom.cas-agd-tlmdcn.ApiGatewayRestApiId}
    restApiRootResourceId: ${self:custom.cas-agd-tlmdcn.ApiGatewayRestApiRootResourceId}
  tracing:
    lambda: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchWriteItem
          Resource: "*"

custom:
  cas-agd-tlmdcn:
    ApiGatewayRestApiId:
      "Fn::ImportValue": cas-agd-tlmdcn-${sls:stage}-ApiGatewayRestApiId
    ApiGatewayRestApiRootResourceId:
      "Fn::ImportValue": cas-agd-tlmdcn-${sls:stage}-ApiGatewayRestApiRootResourceId
  cas-medicap:
    EventBusName:
      "Fn::ImportValue": cas-medicap-${sls:stage}-EventBusName

functions:
  httpAvailabilityGet:
    handler: ./src/application/functions/http-availability-get.handler
    events:
      - http:
          path: /availability
          method: get
          cors: true

  eventMedicapBookingSynced:
    handler: ./src/application/functions/event-medicap-booking-synced.handler
    events:
      - eventBridge:
          eventBus: ${self:custom.cas-medicap.EventBusName}
          pattern:
            source:
              - cas-medicap-sync
            detail-type:
              - booking-synced

  eventMedicapPreBookingSynced:
    handler: ./src/application/functions/event-medicap-pre-booking-synced.handler
    events:
      - eventBridge:
          eventBus: ${self:custom.cas-medicap.EventBusName}
          pattern:
            source:
              - cas-medicap-sync
            detail-type:
              - pre-booking-synced

  eventMedicapReleaseSynced:
    handler: ./src/application/functions/event-medicap-release-synced.handler
    events:
      - eventBridge:
          eventBus: ${self:custom.cas-medicap.EventBusName}
          pattern:
            source:
              - cas-medicap-sync
            detail-type:
              - release-synced

  eventMedicapCalendarSynced:
    handler: ./src/application/functions/event-medicap-calendar-synced.handler
    events:
      - eventBridge:
          eventBus: ${self:custom.cas-medicap.EventBusName}
          pattern:
            source:
              - cas-medicap-sync
            detail-type:
              - calendar-synced

  eventMedicapExceptionSynced:
    handler: ./src/application/functions/event-medicap-exception-synced.handler
    events:
      - eventBridge:
          eventBus: ${self:custom.cas-medicap.EventBusName}
          pattern:
            source:
              - cas-medicap-sync
            detail-type:
              - exception-synced

resources:
  Resources:
    BookingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: date
            AttributeType: S
          - AttributeName: gsi_companyId_officeId_serviceId_professionalId_isEnabled
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: gsi_companyId_officeId_serviceId_professionalId_isEnabled
            KeySchema:
              - AttributeName: gsi_companyId_officeId_serviceId_professionalId_isEnabled
                KeyType: HASH
              - AttributeName: date
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_TABLE_MEDICAP_BOOKING}

    PreBookingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: date
            AttributeType: S
          - AttributeName: gsi_companyId_officeId_serviceId_professionalId_isEnabled
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: gsi_companyId_officeId_serviceId_professionalId_isEnabled
            KeySchema:
              - AttributeName: gsi_companyId_officeId_serviceId_professionalId_isEnabled
                KeyType: HASH
              - AttributeName: date
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_TABLE_MEDICAP_PRE_BOOKING}

    ReleaseTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_TABLE_MEDICAP_RELEASE}

    CalendarTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_TABLE_MEDICAP_CALENDAR}

    ExceptionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_TABLE_MEDICAP_EXCEPTION}
